# Generated by Django 5.1.6 on 2025-02-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='release_year',
            new_name='birth_year',
        ),
    ]
