# Generated by Django 5.1.6 on 2025-02-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_release_year_user_birth_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='name',
        ),
    ]
