name: Deploy Client

on:
  push:
    branches:
      - test-branch
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Build React App
        run: |
          cd client
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync client/dist/ s3://pos-frontend-2200 --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1FIEL69JQ4QVH --paths "/*"
