name: Deploy Client

on:
  push:
    branches:
      - test-branch
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 

      - name: Install Dependencies
        run: |
          cd client
          npm install
          
      - name: Run Test
        run: |
          cd client
          npm tets

      - name: Build React App
        run: |
          cd client
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync client/dist/ s3://pos-frontend-2200 --delete \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1FIEL69JQ4QVH --paths "/index.html"
